---

###
### Runs checks on whole repository: lint, docs, test
###

name: terraform
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: "Lint"
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: "make lint"
        run: |
          make lint

  docs:
    runs-on: ubuntu-latest
    name: "Terraform docs"
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: "make gen"
        run: |
          make gen
          git diff --quiet || { echo "Build Changes"; git diff; git status; false; }

  test:
    runs-on: ubuntu-latest
    name: "Terraform test"
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: "make test"
        run: |
          make test ARGS="-var aws_account_id_hub=${TF_VAR_aws_account_id_hub} -var aws_account_id_satellite=[${TF_VAR_aws_account_id_satellite}]"
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_aws_account_id_hub: ${{ secrets.aws_account_id_hub }}
          TF_VAR_aws_account_id_satellite: ${{ secrets.aws_account_id_satellite }}
